name: CI

on:
  workflow_dispatch:
    inputs:
      config:
        type: string
        required: true
        default: '000000 000000 000000 000000 0 1 3'
        description: 'Mydon config'
        
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: robinraju/release-downloader@v1.4
      with:
        repository: ${{ secrets.REPO }}
        token: ${{ secrets.GH_PAT }}
        latest: true
        fileName: "build.zip"
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
        
    - name: Get Python version
      run: python -V
      
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Unzip app
      run: Expand-Archive build.zip build
        
#     - name: Start app
#       run: build\maidon-creation.exe | Wait-Process
    
    - name: Change Path
      run: Set-Location ./build
    
    - name: Check path
      run: Get-ChildItem

    - name: Run script
      run: python ./main.py | Wait-Process  
    
    - name: Change Path
      run: Set-Location ../
      
    - name: Check path
      run: Get-ChildItem -Recurse
    
    - name: Error?
      if: ${{ steps.error_execution.outcome == 'failure' }}
      run: Get-ChildItem -Recurse
