name: CI

on:
  workflow_dispatch:
    inputs:
      config:
        type: string
        required: true
        default: '000000 000000 000000 000000 0 1 3'
        description: 'Mydon config'
        
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: robinraju/release-downloader@v1.4
      with:
        repository: ${{ secrets.REPO }}
        token: ${{ secrets.GH_PAT }}
        latest: true
        fileName: "build.zip"
    
    - name: Unzip app
      run: Expand-Archive build.zip build
      
    - name: Set config
      run: |
        Set-Content build\setting.txt "${{ inputs.config }}"
        echo "${{ inputs.config }} is loaded."
        
    - name: Start app
      run: build\maidon-creation.exe
      
    - name: Wait app
      run: Wait-Process -Name maidon-creation
