name: CI

on:
  workflow_dispatch:
    inputs:
      config:
        type: string
        required: true
        default: '000000 000000 000000 000000 0 1 3'
        description: 'Mydon config'
      tags:
        description: 'Mydon id'
        required: true 
        type: string
        
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: robinraju/release-downloader@v1.4
      with:
        repository: ${{ secrets.REPO }}
        token: ${{ secrets.GH_PAT }}
        latest: true
        fileName: "build.zip"
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'

    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Unzip app
      run: Expand-Archive build.zip build
        
#     - name: Start app
#       run: build\maidon-creation.exe | Wait-Process
    
    - name: Check path
      run: Get-ChildItem
      working-directory: ./build
      
    - name: Run script
      run: python main.py
      working-directory: ./build
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with: 
        body: ${{ inputs.config }}
        prerelease: True
        files: |
            ./build/120FPS.zip
            ./build/120FPS_light.zip
            ./build/60FPS.zip
            ./build/daijiro.zip
        name: ${{ inputs.tags }}
        tag_name: ${{ inputs.tags }}
        repository: ${{ secrets.DON_REPO }}
        token: ${{ secrets.GH_PAT }}

    - name: Error?
      if: ${{ steps.error_execution.outcome == 'failure' }}
      run: Get-ChildItem -Recurse
