name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: robinraju/release-downloader@v1.4
      with:
        repository: ""
        token: ""
        latest: true
        fileName: "build.zip"
